from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    content = file.read_text()
    count = content.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one anchor, found {count}: {old[:180]!r}")
    file.write_text(content.replace(old, new, 1))


replace_once(
    "flowcordia/runbooks/release-acceptance.md",
    '''The schema `0.2` evidence boundary has passed deterministic transformation, formatting, connected acceptance contract tests, release-manifest and assembly tests, Playwright test discovery, Prisma generation, the FlowCordia workflow-package build, and the full monorepo typecheck on one exact branch head. Temporary validation workflows, scripts, and diagnostics are excluded from review.\n\nThese checks prove the harness and mixed-version manifest contract. They do not prove a connected deployment. Release evidence is valid only after a protected environment produces a real preview artifact for the exact application commit, proposal head, verified run, and positive HTTP, mapping, and ready-credential counts.\n''',
    '''The schema `0.3` evidence boundary has passed deterministic transformation, formatting, operational-canary validation, connected acceptance contract tests, release-manifest and assembly tests, Playwright test discovery, Prisma generation, the FlowCordia workflow-package build, and the full monorepo typecheck on one exact branch head. Temporary validation workflows, scripts, and diagnostics are excluded from review.\n\nThese checks prove the harness and mixed-source manifest contract. They do not prove a configured deployment. Release evidence is valid only after protected environments produce real provider and alert artifacts for the exact release/application plus the five connected lifecycle artifacts for the exact proposal, deployment, rollback, and verified runs.\n''',
)
replace_once(
    "flowcordia/runbooks/release-acceptance.md",
    '''After all five protected connected stages pass, run **Flowcordia assemble release evidence** from `main` with their exact workflow run IDs. Follow `flowcordia/testing/release-evidence-registry.md` to configure the protected environment, validate the generated draft pull request, and independently review the canonical digest.\n\nThe assembler accepts only successful official `main`-branch workflow runs, derives rather than trusts artifact names, validates the exact journey lineage, and refuses to overwrite an existing release branch or manifest path. It commits nothing directly to `main`.\n''',
    '''Run **Flowcordia provider readiness** and **Flowcordia alert readiness** first for the exact release/application, then complete the five protected connected stages. Run **Flowcordia assemble release evidence** from `main` with one strict JSON object containing the seven exact workflow run IDs. Follow `flowcordia/testing/release-evidence-registry.md` to configure the protected environments, validate the generated draft pull request, and independently review the canonical digest.\n\nThe assembler accepts only successful official `main`-branch workflow runs, derives rather than trusts artifact names, requires provider and alert evidence no older than 24 hours at assembly, validates exact application/release identity and the connected journey lineage, and refuses to overwrite an existing release branch or manifest path. It commits nothing directly to `main`.\n''',
)
replace_once(
    "flowcordia/runbooks/release-acceptance.md",
    '''- generic provider metadata;\n''',
    '''- provider response bodies, provider errors, addresses, endpoints, or credentials;\n''',
)

replace_once(
    "flowcordia/testing/release-evidence-registry.md",
    '''The registry assembles five protected acceptance artifacts into one exact-lineage release manifest. The preview artifact must additionally prove the release workflow contains at least one approved HTTP node, one deterministic mapping node, and one ready credential binding before its exact-head run can authorize assembly.\n\nThis registry proves the connected journey already covered by the acceptance harnesses. It does not turn missing acceptance into a pass, execute a workflow, merge a product proposal, deploy code, or perform rollback.\n''',
    '''The registry assembles two protected operational-canary artifacts and five protected connected-acceptance artifacts into one exact-lineage release manifest. The provider and alert artifacts must be fresh, exact-application READY results; the preview artifact must additionally prove the release workflow contains at least one approved HTTP node, one deterministic mapping node, and one ready credential binding before its exact-head run can authorize assembly.\n\nThis registry proves the operational prerequisites and connected journey already covered by the protected harnesses. It does not turn missing acceptance into a pass, execute a workflow, merge a product proposal, deploy code, perform rollback, prove inbox delivery, prove queued alert-worker consumption, or replace recovery/upgrade evidence.\n''',
)
replace_once(
    "flowcordia/testing/release-evidence-registry.md",
    '''1. **Flowcordia connected acceptance** in `preview` mode.\n2. **Flowcordia governed promotion acceptance** for the same proposal head.\n3. **Flowcordia production acceptance** in `production` mode for the resulting merge.\n4. **Flowcordia rollback proposal acceptance** for that current production proposal and one earlier reviewed target.\n5. Review and merge the generated rollback proposal normally, then run **Flowcordia production acceptance** in `rollback_production` mode for the new rollback proposal head and its new merge commit.\n''',
    '''1. **Flowcordia provider readiness** for the exact deployed application and controlled operator mailbox.\n2. **Flowcordia alert readiness** for the same release/application and one exact production channel.\n3. **Flowcordia connected acceptance** in `preview` mode.\n4. **Flowcordia governed promotion acceptance** for the same proposal head.\n5. **Flowcordia production acceptance** in `production` mode for the resulting merge.\n6. **Flowcordia rollback proposal acceptance** for that current production proposal and one earlier reviewed target.\n7. Review and merge the generated rollback proposal normally, then run **Flowcordia production acceptance** in `rollback_production` mode for the new rollback proposal head and its new merge commit.\n''',
)
replace_once(
    "flowcordia/testing/release-evidence-registry.md",
    '''- the five successful workflow run IDs in journey order.\n\nArtifact names are not operator inputs. The workflow derives their exact official names from the stage, workflow or proposal identity, and run ID.\n''',
    '''- one strict JSON object containing exactly the seven successful run IDs keyed by `provider`, `alert`, `preview`, `promotion`, `production`, `rollback_proposal`, and `rollback_production`.\n\nArtifact names are not operator inputs. The workflow derives their exact official names from the release, stage, workflow or proposal identity, and run ID. Provider and alert run IDs must be distinct from every connected-stage run.\n''',
)
replace_once(
    "flowcordia/testing/release-evidence-registry.md",
    '''The manifest rejects unsupported fields and recursively rejects payloads, outputs, credentials, browser state, provider data, internal IDs, reasons, stack traces, and raw errors. Every source must have result `PASSED`, stage `complete`, the same application commit, and the same workflow ID.\n\nThe accepted chain binds:\n''',
    '''The manifest rejects unsupported fields and recursively rejects payloads, outputs, credentials, browser state, provider responses/errors, internal IDs, reasons, stack traces, and raw errors. Provider and alert artifacts use their own exact READY schemas; the five connected sources must have result `PASSED`, stage `complete`, the same application commit, and the same workflow ID.\n\nThe accepted chain binds:\n\n- provider release configuration, object-store access, and product-email acceptance to the exact application commit;\n- alert worker Redis, exact production-channel coverage/backlog, and fixed canary acceptance to the exact release and application commit;\n- provider before alert, alert before preview, and both operational artifacts to a maximum 24-hour age at assembly;\n''',
)
replace_once(
    "flowcordia/testing/release-evidence-registry.md",
    '''This five-stage manifest is necessary connected release evidence, but it does not by itself satisfy every private-beta or public-beta gate in `flowcordia/product/release-readiness.md`. Repository CI, installation and recovery proof, product usability evidence, performance and isolation tests, and any additional release-record fields required by the advertised maturity level remain separate stop-ship gates.\n''',
    '''This seven-source schema `0.3` manifest is necessary operational and connected release evidence, but it does not by itself satisfy every private-beta or public-beta gate in `flowcordia/product/release-readiness.md`. Repository CI, live dependency health, database recovery, controlled upgrade proof, product usability evidence, queued-alert consumption, human incident response, performance, isolation, and any additional release-record fields required by the advertised maturity level remain separate stop-ship gates.\n''',
)

replace_once(
    "flowcordia/product/release-readiness.md",
    '''| Core provider readiness | Implemented as a bounded manual preflight | Existing object-store client verifies bucket access without writes; existing general email client submits one fixed explicitly confirmed message; a configured release run remains required |\n| Alert readiness | Implemented as a protected bounded canary | Existing alerts-worker Redis and one exact production email, Slack, or webhook channel must satisfy failure coverage and backlog policy before accepting one fixed canary; a configured protected run remains required |\n| Installation and operations | Partial | Executed controlled migrations, durable object-write proof, inbox/deliverability evidence, queued alert-worker consumption, human acknowledgement/escalation, PITR, off-site recovery, automated upgrades, and connected release evidence remain required |\n''',
    '''| Core provider readiness | Implemented as a protected bounded canary and mandatory release-manifest source | Existing object-store client verifies bucket access without writes; existing general email client submits one fixed explicitly confirmed message; exact READY evidence is bound to the application commit with a 24-hour assembly freshness window |\n| Alert readiness | Implemented as a protected bounded canary and mandatory release-manifest source | Existing alerts-worker Redis and one exact production email, Slack, or webhook channel must satisfy failure coverage and backlog policy before accepting one fixed canary; exact READY evidence is bound to the release/application with a 24-hour assembly freshness window |\n| Immutable release evidence | Implemented as schema `0.3` | Seven distinct official main-branch runs—provider, alert, preview, promotion, production, rollback proposal, and rollback production—are validated, digested, ordered, and proposed as one no-overwrite manifest |\n| Installation and operations | Partial | Executed controlled migrations, durable object-write proof, inbox/deliverability evidence, queued alert-worker consumption, human acknowledgement/escalation, live dependency/recovery/upgrade evidence binding, PITR, off-site recovery, and automated upgrades remain required |\n''',
)
replace_once(
    "flowcordia/product/release-readiness.md",
    '''- FlowCordia application commit;\n''',
    '''- FlowCordia application commit and unique release ID;\n- fresh provider transport/object-store mode and alert channel/backlog summaries from exact protected runs;\n''',
)
replace_once(
    "flowcordia/product/release-readiness.md",
    '''- The connected acceptance run proves application configuration, GitHub installation, preview build, deployment discovery, task execution, evidence projection, promotion, and rollback.\n- Neither form of evidence replaces the others.\n''',
    '''- The connected acceptance run proves application configuration, GitHub installation, preview build, deployment discovery, task execution, evidence projection, promotion, and rollback.\n- The schema `0.3` release manifest proves the exact provider/alert canaries and five connected lifecycle sources were official, fresh where required, distinct, digest-bound, chronological, and tied to one application/release lineage. It does not replace live dependency, recovery, upgrade, usability, or incident-response evidence.\n- Neither form of evidence replaces the others.\n''',
)

replace_once(
    "flowcordia/product/capability-matrix.md",
    '''| Alert readiness canary | Existing alerts worker Redis, project alert channels, and email/Slack/webhook delivery adapters | Exact application/project/channel binding, production task/deployment-failure coverage, bounded pending backlog, one confirmed fixed canary, protected workflow, and redacted evidence delivered; queued-worker consumption, downstream visibility, acknowledgement, escalation, and load behavior remain separate |\n| Self-hosting | Guided setup over existing Docker/Kubernetes topology | Deterministic configuration, live-dependency, database recovery, controlled-upgrade, provider-readiness, and alert-readiness gates plus install ordering delivered; automated mutation, HA, PITR, and DR remain planned |\n''',
    '''| Alert readiness canary | Existing alerts worker Redis, project alert channels, and email/Slack/webhook delivery adapters | Exact application/project/channel binding, production task/deployment-failure coverage, bounded pending backlog, one confirmed fixed canary, protected workflow, and redacted evidence delivered; queued-worker consumption, downstream visibility, acknowledgement, escalation, and load behavior remain separate |\n| Immutable release evidence | Two operational canaries plus five connected lifecycle stages | Schema `0.3` requires distinct official main-branch provider, alert, preview, promotion, production, rollback-proposal, and rollback-production artifacts with exact names/digests, application/release binding, 24-hour operational freshness, chronology, and no-overwrite evidence PR |\n| Self-hosting | Guided setup over existing Docker/Kubernetes topology | Deterministic configuration, live-dependency, database recovery, controlled-upgrade, provider-readiness, alert-readiness, and immutable seven-source release evidence plus install ordering delivered; automated mutation, HA, PITR, and DR remain planned |\n''',
)

replace_once(
    "flowcordia/connections/README.md",
    '''| Provider readiness preflight | Existing packet `ObjectStoreClient` and general product `EmailClient` | Verify bucket access without object mutation, then submit one explicitly authorized fixed email only after all read-only gates pass | Schema `0.1` object-first CLI implemented with null-transport rejection, fixed projections, and no provider-value output; a configured run remains mandatory |\n| Alert readiness preflight | Existing alerts-worker Redis, project alert channel, and alert email/Slack/webhook adapters | Prove exact deployed identity, worker queue reachability, production failure coverage, bounded backlog, and one explicitly confirmed fixed canary without serializing delivery targets | Schema `0.1` protected main-only canary implemented; direct adapter acceptance is preserved while queued-worker consumption and human response remain separate |\n''',
    '''| Provider readiness preflight | Existing packet `ObjectStoreClient`, general product `EmailClient`, and immutable release assembler | Verify bucket access without object mutation, submit one explicitly authorized fixed email, and preserve an exact application-bound official artifact | Schema `0.1` CLI plus protected main-only workflow delivered; READY evidence is a mandatory schema `0.3` release-manifest source while inbox delivery and durable writes remain separate |\n| Alert readiness preflight | Existing alerts-worker Redis, project alert channel, alert email/Slack/webhook adapters, and immutable release assembler | Prove exact deployed identity, worker queue reachability, production failure coverage, bounded backlog, one explicitly confirmed fixed canary, and preserve an exact release/application-bound official artifact | Schema `0.1` protected main-only canary delivered; READY evidence is a mandatory schema `0.3` release-manifest source while queued-worker consumption and human response remain separate |\n| Immutable release assembler | Provider/alert canaries and preview/promotion/production/rollback acceptance artifacts | Bind two fresh operational prerequisites and five connected lifecycle proofs into one canonical no-overwrite public-safe manifest | Schema `0.3` seven-source official-run validation, exact artifact naming/digests, chronology, canonical digest, protected recovery artifact, and reviewable evidence PR delivered |\n''',
)
